import { normalizeLocale, type LocaleCode } from "./locale";

const keys = ["language","back","settingsTitle","settingsDescription","apply","applying","contentNote","login","heroTitle","heroDescription","browse","chat","places","people","airports","search","searchPlaceholder","airport","find","all","palace","fortress","historic","museum","nature","recommended","empty","detail","game","gameSoon","send","message","thinking","chatError","aiNote","about","ask","chatHint","gameChoiceTitle","nextStory","timePasses"] as const;

const rows: Record<LocaleCode,string[]> = {
ko:["언어","여행지로 돌아가기","더 편안한 언어로 만나요.","Histour에서 사용할 언어를 선택해 주세요.","이 언어로 시작하기","적용 중…","장소·인물 소개와 고정 게임 대사는 한국어가 포함될 수 있습니다.","로그인","이야기 속으로 떠나는 역사 여행","AI 역사 인물과 대화하고 한국의 역사 장소를 만나보세요.","장소 둘러보기","대화하기","역사 여행지","인물 대화","공항 기준","장소 검색","장소, 인물 또는 이야기 검색","공항 기준","장소 찾기","전체","궁궐","성곽","유적지","박물관","자연/정원","지금 떠나기 좋은 역사 장소","조건에 맞는 장소가 없습니다. 검색어나 필터를 조정해 주세요.","자세히 보기","게임하기","게임 준비 중","전송","메시지 보내기","답변을 생각하고 있어요…","답변을 받지 못했어요. 다시 전송해 주세요.","역사 인물을 재현한 AI 대화이며 실제 발언과 다를 수 있습니다.","인물과 장소 소개","궁금한 이야기를 물어보세요","인물의 삶과 이 장소에 대해 자유롭게 이야기해 보세요.","어떻게 대답할까?","다음 이야기 →","시간이 흐르고..."],
en:["Language","Back to exploring","Your language, your journey.","Choose your language for Histour.","Apply language","Applying…","Place descriptions, biographies and scripted game dialogue may include Korean.","Log in","A journey through places and stories","Talk with AI historical figures and explore Korea’s historic places.","Explore places","Chat","Historic places","Figure chats","Airports","Search places","Search places, people or stories","Airport","Find places","All","Palaces","Fortresses","Historic sites","Museums","Nature / Gardens","Historic places to explore","No places match. Try another search or filter.","View details","Play game","Game coming soon","Send","Send a message","Thinking…","Could not get a reply. Please send again.","AI recreates historical figures; dialogue is not an actual quotation.","About the person and place","What would you like to know?","Ask about their life or the story of this place.","How should I respond?","Next story →","Time passes..."],
ja:["言語","観光地に戻る","あなたの言葉で、旅を。","Histourで使用する言語を選んでください。","この言語で始める","適用中…","場所・人物紹介やゲームの固定台詞には韓国語が含まれる場合があります。","ログイン","物語とともに歴史を旅する","AI歴史人物と話し、韓国の歴史ある場所を巡りましょう。","観光地を探す","会話する","歴史スポット","人物との会話","空港","場所を検索","場所・人物・物語を検索","空港から探す","検索","すべて","宮殿","城郭","史跡","博物館","自然・庭園","訪れたい歴史スポット","条件に合う場所がありません。検索条件を変更してください。","詳しく見る","ゲームをする","ゲーム準備中","送信","メッセージを入力","考えています…","返信を取得できませんでした。もう一度送信してください。","歴史人物を再現したAIとの会話であり、実際の発言ではありません。","人物と場所の紹介","知りたいことを聞いてみましょう","人物の生涯やこの場所の物語を自由に尋ねてください。","どう答えよう？","次の物語へ →","時が流れ..."],
"zh-Hans":["语言","返回景点","用熟悉的语言，开启旅程。","请选择您在 Histour 使用的语言。","使用此语言","正在应用…","景点介绍、人物简介和游戏固定台词可能包含韩语。","登录","走进故事，探索历史","与 AI 历史人物交谈，探索韩国的历史景点。","探索景点","开始对话","历史景点","人物对话","机场","搜索景点","搜索地点、人物或故事","按机场筛选","查找景点","全部","宫殿","城墙","历史遗址","博物馆","自然 / 庭园","值得探索的历史景点","没有符合条件的景点，请调整搜索或筛选条件。","查看详情","开始游戏","游戏即将上线","发送","输入消息","正在思考…","无法获取回复，请重新发送。","AI 模拟历史人物，内容并非真实历史发言。","人物与景点简介","您想了解什么？","自由询问人物生平或这个地方的故事。","该怎么回答？","下一个故事 →","时间流逝..."],
"zh-Hant":["語言","返回景點","用熟悉的語言，開啟旅程。","請選擇您在 Histour 使用的語言。","使用此語言","正在套用…","景點介紹、人物簡介和遊戲固定台詞可能包含韓語。","登入","走進故事，探索歷史","與 AI 歷史人物交談，探索韓國的歷史景點。","探索景點","開始對話","歷史景點","人物對話","機場","搜尋景點","搜尋地點、人物或故事","依機場篩選","尋找景點","全部","宮殿","城牆","歷史遺址","博物館","自然 / 庭園","值得探索的歷史景點","沒有符合條件的景點，請調整搜尋或篩選條件。","查看詳情","開始遊戲","遊戲即將推出","傳送","輸入訊息","正在思考…","無法取得回覆，請重新傳送。","AI 模擬歷史人物，內容並非真實歷史發言。","人物與景點簡介","您想了解什麼？","自由詢問人物生平或這個地方的故事。","該怎麼回答？","下一個故事 →","時間流逝..."],
th:["ภาษา","กลับไปดูสถานที่","เริ่มการเดินทางในภาษาของคุณ","เลือกภาษาที่ต้องการใช้ใน Histour","ใช้ภาษานี้","กำลังใช้…","ข้อมูลสถานที่ บุคคล และบทเกมบางส่วนอาจยังเป็นภาษาเกาหลี","เข้าสู่ระบบ","เดินทางผ่านสถานที่และเรื่องราว","พูดคุยกับบุคคลในประวัติศาสตร์ผ่าน AI และสำรวจสถานที่ในเกาหลี","สำรวจสถานที่","สนทนา","สถานที่ประวัติศาสตร์","สนทนากับบุคคล","สนามบิน","ค้นหาสถานที่","ค้นหาสถานที่ บุคคล หรือเรื่องราว","เลือกสนามบิน","ค้นหา","ทั้งหมด","พระราชวัง","ป้อมปราการ","โบราณสถาน","พิพิธภัณฑ์","ธรรมชาติ / สวน","สถานที่ประวัติศาสตร์น่าเที่ยว","ไม่พบสถานที่ที่ตรงกัน ลองเปลี่ยนคำค้นหาหรือตัวกรอง","ดูรายละเอียด","เล่นเกม","เกมกำลังจะมา","ส่ง","พิมพ์ข้อความ","กำลังคิด…","ไม่สามารถรับคำตอบได้ กรุณาส่งอีกครั้ง","บทสนทนาจำลองโดย AI ไม่ใช่คำพูดจริงของบุคคลในประวัติศาสตร์","เกี่ยวกับบุคคลและสถานที่","คุณอยากรู้อะไร?","ถามเกี่ยวกับชีวิตของบุคคลหรือเรื่องราวของสถานที่นี้ได้เลย","จะตอบอย่างไรดี?","เรื่องถัดไป →","เวลาผ่านไป..."],
vi:["Ngôn ngữ","Quay lại khám phá","Hành trình bằng ngôn ngữ của bạn.","Chọn ngôn ngữ bạn muốn dùng trên Histour.","Áp dụng ngôn ngữ","Đang áp dụng…","Giới thiệu địa điểm, nhân vật và lời thoại có sẵn trong trò chơi có thể còn bằng tiếng Hàn.","Đăng nhập","Khám phá lịch sử qua những câu chuyện","Trò chuyện với nhân vật lịch sử AI và khám phá các địa điểm ở Hàn Quốc.","Khám phá địa điểm","Trò chuyện","Địa điểm lịch sử","Trò chuyện nhân vật","Sân bay","Tìm địa điểm","Tìm địa điểm, nhân vật hoặc câu chuyện","Theo sân bay","Tìm kiếm","Tất cả","Cung điện","Thành lũy","Di tích","Bảo tàng","Thiên nhiên / Vườn","Địa điểm lịch sử đáng khám phá","Không có địa điểm phù hợp. Hãy đổi từ khóa hoặc bộ lọc.","Xem chi tiết","Chơi trò chơi","Trò chơi sắp ra mắt","Gửi","Nhập tin nhắn","Đang suy nghĩ…","Không nhận được phản hồi. Vui lòng gửi lại.","AI mô phỏng nhân vật lịch sử; đây không phải lời nói thực tế.","Giới thiệu nhân vật và địa điểm","Bạn muốn tìm hiểu điều gì?","Hỏi về cuộc đời nhân vật hoặc câu chuyện của địa điểm này.","Nên trả lời thế nào?","Câu chuyện tiếp theo →","Thời gian trôi qua..."],
ru:["Язык","Назад к местам","Путешествуйте на своём языке.","Выберите язык для Histour.","Применить язык","Применение…","Описания мест, биографии и готовые игровые диалоги могут содержать корейский текст.","Войти","Путешествие по местам и историям","Общайтесь с историческими персонажами ИИ и исследуйте Корею.","Открыть места","Общаться","Исторические места","Беседы с персонажами","Аэропорты","Поиск мест","Места, люди или истории","По аэропорту","Найти","Все","Дворцы","Крепости","Исторические объекты","Музеи","Природа / Сады","Исторические места для путешествия","Места не найдены. Измените запрос или фильтры.","Подробнее","Играть","Игра скоро появится","Отправить","Введите сообщение","Думаю…","Не удалось получить ответ. Отправьте сообщение ещё раз.","ИИ воссоздаёт исторических персонажей; диалоги не являются подлинными цитатами.","О персонаже и месте","Что вы хотите узнать?","Спросите о жизни персонажа или истории этого места.","Как ответить?","Следующая история →","Проходит время..."],
fr:["Langue","Retour aux lieux","Voyagez dans votre langue.","Choisissez votre langue pour Histour.","Appliquer la langue","Application…","Les descriptions, biographies et dialogues prédéfinis peuvent contenir du coréen.","Connexion","Un voyage au fil des lieux et des récits","Discutez avec des personnages historiques IA et explorez la Corée.","Explorer les lieux","Discuter","Lieux historiques","Conversations","Aéroports","Rechercher un lieu","Lieux, personnages ou récits","Par aéroport","Rechercher","Tous","Palais","Forteresses","Sites historiques","Musées","Nature / Jardins","Lieux historiques à découvrir","Aucun lieu trouvé. Modifiez la recherche ou les filtres.","Voir les détails","Jouer","Jeu à venir","Envoyer","Écrire un message","Réflexion en cours…","Impossible d’obtenir une réponse. Veuillez réessayer.","L’IA recrée des personnages historiques ; les dialogues ne sont pas des citations authentiques.","Le personnage et le lieu","Que souhaitez-vous savoir ?","Posez des questions sur sa vie ou sur l’histoire de ce lieu.","Que répondre ?","Histoire suivante →","Le temps passe..."],
de:["Sprache","Zurück zu den Orten","Reisen Sie in Ihrer Sprache.","Wählen Sie Ihre Sprache für Histour.","Sprache anwenden","Wird angewendet…","Ortsbeschreibungen, Biografien und vorgegebene Spieldialoge können koreanischen Text enthalten.","Anmelden","Eine Reise durch Orte und Geschichten","Sprechen Sie mit KI-Geschichtsfiguren und entdecken Sie Korea.","Orte entdecken","Chatten","Historische Orte","Gespräche","Flughäfen","Orte suchen","Orte, Personen oder Geschichten","Nach Flughafen","Suchen","Alle","Paläste","Festungen","Historische Stätten","Museen","Natur / Gärten","Historische Orte entdecken","Keine passenden Orte. Ändern Sie Suche oder Filter.","Details ansehen","Spielen","Spiel folgt bald","Senden","Nachricht schreiben","Denke nach…","Keine Antwort erhalten. Bitte erneut senden.","KI stellt historische Personen nach; die Dialoge sind keine echten Zitate.","Über Person und Ort","Was möchten Sie wissen?","Fragen Sie nach dem Leben der Person oder der Geschichte dieses Ortes.","Wie antworten?","Nächste Geschichte →","Die Zeit vergeht..."],
es:["Idioma","Volver a explorar","Viaja en tu idioma.","Elige el idioma que prefieras para Histour.","Aplicar idioma","Aplicando…","Las descripciones, biografías y diálogos predefinidos pueden incluir coreano.","Iniciar sesión","Un viaje por lugares e historias","Habla con personajes históricos de IA y explora Corea.","Explorar lugares","Conversar","Lugares históricos","Conversaciones","Aeropuertos","Buscar lugares","Lugares, personajes o historias","Por aeropuerto","Buscar","Todos","Palacios","Fortalezas","Sitios históricos","Museos","Naturaleza / Jardines","Lugares históricos para explorar","No hay lugares que coincidan. Cambia la búsqueda o los filtros.","Ver detalles","Jugar","Juego próximamente","Enviar","Escribe un mensaje","Pensando…","No se pudo obtener una respuesta. Vuelve a enviar el mensaje.","La IA recrea personajes históricos; los diálogos no son citas reales.","Sobre el personaje y el lugar","¿Qué te gustaría saber?","Pregunta por su vida o por la historia de este lugar.","¿Cómo responder?","Siguiente historia →","El tiempo pasa..."],
};

export function getCopy(lang?: string|null) {
  const row=rows[normalizeLocale(lang)];
  return Object.fromEntries(keys.map((key,index)=>[key,row[index]])) as Record<typeof keys[number],string>;
}

export const languageNames: Record<LocaleCode,string>={ko:"Korean",en:"English",ja:"Japanese","zh-Hans":"Simplified Chinese","zh-Hant":"Traditional Chinese",th:"Thai",vi:"Vietnamese",ru:"Russian",fr:"French",de:"German",es:"Spanish"};